board:
  black_pieces: BlackPieces.png
  image: board_plain_02.png
  size: 800
  white_pieces: WhitePieces.png
game:
  font_name: clarity.ttf
  grid_font_size: 10
  label_font_size: 20
  music: true
  music_vol: 0.4
  players: 1
  show_debug: false
  show_grid: false
  show_labels: true
  show_positions: false
  sound: true
  sound_vol: 1.0
  soundtrack: clouds.mp3
piece:
  size_x: 90
  size_y: 90
state:
  last_fen: rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1
