game:
  players: 1 # valid values are 1, 2
  sound: false
  music: true
  soundtrack: "clouds.mp3"
  show_grid: true
  show_positions: true
  grid_font_name: "clarity.ttf"
  grid_font_size: 10

board:
  image: "board_plain_02.png"
  white_pieces: "WhitePieces.png"
  black_pieces: "BlackPieces.png"
  size: 800 # pixels

piece:
  size_x: 90
  size_y: 90
