board:
  black_pieces: BlackPieces.png
  image: board_plain_02.png
  size: 800
  white_pieces: WhitePieces.png
cpu:
  ai: piece_squares2
  complexity: 3
  delay: 1000
  stockfish_path: assets/engines/stockfish
game:
  font_name: clarity.ttf
  grid_font_size: 10
  label_font_size: 20
  music: true
  music_vol: 0.4
  player1: human
  player2: cpu
  show_debug: false
  show_grid: false
  show_labels: true
  show_positions: false
  sound: true
  sound_vol: 1.0
  soundtrack: clouds.mp3
piece:
  size_x: 90
  size_y: 90
state:
  last_fen: 3k2r1/pP1P1pNp/2b5/2pP2PP/8/8/2B2P2/R3K2R b KQ - 16 46
