board:
  black_pieces: BlackPieces.png
  image: board_plain_02.png
  size: 800
  white_pieces: WhitePieces.png
game:
  font_name: clarity.ttf
  grid_font_size: 10
  label_font_size: 20
  music: true
  music_vol: 0.4
  player1: human
  player2: cpu
  show_debug: false
  show_grid: false
  show_labels: true
  show_positions: false
  sound: true
  sound_vol: 1.0
  soundtrack: clouds.mp3
cpu:
  ai: piece_squares
  delay: 2000
piece:
  size_x: 90
  size_y: 90
state:
  last_fen: r1bqkb1r/ppp1pppp/3p4/2nP4/8/8/PPP2PPP/RNB1KBNR w KQkq - 0 7
