board:
  black_pieces: BlackPieces.png
  image: board_plain_02.png
  size: 800
  white_pieces: WhitePieces.png
  show_possible_moves: true
cpu:
  ai: piece_squares2
  complexity: 3
  delay: 1000
  stockfish_path: assets/engines/stockfish
  openai_api_key: ""
game:
  font_name: clarity.ttf
  grid_font_size: 10
  label_font_size: 20
  music: true
  music_vol: 0.4
  player1: human
  player2: cpu
  show_debug: false
  show_grid: false
  show_labels: true
  show_positions: false
  sound: true
  sound_vol: 1.0
  soundtrack: clouds.mp3
  undo_last_move_allowed: true
piece:
  size_x: 90
  size_y: 90
state:
  last_fen: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
