board:
  black_pieces: BlackPieces.png
  image: board_plain_02.png
  size: 800
  white_pieces: WhitePieces.png
game:
  cpu_enabled: true
  font_name: clarity.ttf
  grid_font_size: 10
  label_font_size: 20
  music: true
  music_vol: 0.4
  player1: human
  player2: cpu
  show_debug: false
  show_grid: false
  show_labels: true
  show_positions: false
  sound: true
  sound_vol: 1.0
  soundtrack: clouds.mp3
piece:
  size_x: 90
  size_y: 90
state:
  last_fen: 8/2N1Q3/1N6/p3BB1p/1p3P1k/4P3/P2P3P/R3K3 b Q - 2 39
