game:
  players: 1 # valid values are 1, 2
  sound: true
  music: false
  sound_vol: 1.0
  music_vol: 0.4
  soundtrack: "clouds.mp3"
  show_grid: false
  show_positions: false
  font_name: "clarity.ttf"
  grid_font_size: 10
  label_font_size: 20
  show_labels: true

board:
  image: "board_plain_02.png"
  white_pieces: "WhitePieces.png"
  black_pieces: "BlackPieces.png"
  size: 800 # pixels

piece:
  size_x: 90
  size_y: 90
